[project]
name = "photos"
version = "0.2.0"
description = "Copy photos marked as favorites to the wallpaper folder"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyexiv2>=2.15.4",
]
